# Generated by Django 3.2.8 on 2022-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='djasd', upload_to='profile_picture'),
            preserve_default=False,
        ),
    ]
