version: "3.8"

volumes:
    app_data:
        name: k9archiver_app_data
    static_files:
        name: k9archiver_static_files
    media_files:
        name: k9archiver_media_files
    certbot_web:
        name: k9archiver_certbot_web
    certbot_certs:
        name: k9archiver_certbot_certs

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        image: archiver:production
        container_name: k9archiver_django_production
        command: /app/docker/start.sh server
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - static_files:/app/staticfiles
            - media_files:/app/media

    postgres:
        image: postgres:13.3-alpine
        container_name: k9archiver_postgres_production
        volumes:
            - app_data:/var/lib/postgresql/data
        env_file:
            - .env
    
    
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:production
        container_name: k9archiver_nginx_production
        ports:
            - 80:80
            - 443:443
        depends_on:
            - django
        env_file:
            - .env
        volumes:
            - static_files:/app/staticfiles:ro
            - media_files:/app/media:ro
            - certbot_web:/vol/www:ro
            - certbot_certs:/etc/letsencrypt/:ro

    certbot:
            build:
              context: ./certbot
            command: certbot certonly --webroot --webroot-path "/vol/www/" -d "$DOMAIN" --email $EMAIL --rsa-key-size 4096 --agree-tos --noninteractive
            depends_on:
              - nginx
            env_file:
              - .env
            volumes:
              - certbot_web:/vol/www:rw
              - certbot_certs:/etc/letsencrypt/:rw
            