version: "3.8"

volumes:
    app_data_django:
        name: k9archiver_app_data_django
    app_data_postgres:
        name: k9archiver_app_data_postgres
    static_files:
        name: k9archiver_static_files
    media_files:
        name: k9archiver_media_files
    certbot_web:
        name: k9archiver_certbot_web
    certbot_certs:
        name: k9archiver_certbot_certs
    nginx_conf:
        name: k9archiver_nginx_conf

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        image: archiver:production
        container_name: k9archiver_django_production
        command: /app/docker/start.sh server
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - static_files:/app/staticfiles
            - media_files:/app/media
            - app_data_django:/var/tmp/

    postgres:
        image: postgres:13.3-alpine
        container_name: k9archiver_postgres_production
        volumes:
            - app_data_postgres:/var/lib/postgresql/data
        env_file:
            - .env
    
    
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:production
        container_name: k9archiver_nginx_production
        ports:
            - 80:80
            - 443:443
        depends_on:
            - django
        env_file:
            - .env
        volumes:
            - static_files:/app/staticfiles:ro
            - media_files:/app/media:ro
            - certbot_web:/vol/www:ro
            - certbot_certs:/etc/letsencrypt/:ro
            - nginx_conf:/etc/nginx/:rw

    certbot:
        container_name: k9archiver_certbot_production      
        build:
            context: ./certbot
        depends_on:
            - nginx
        env_file:
            - .env
        volumes:
            - certbot_web:/vol/www:rw
            - certbot_certs:/etc/letsencrypt/:rw
            - nginx_conf:/etc/nginx/:rw
        restart: unless-stopped
            