# Generated by Django 3.2.8 on 2021-11-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_auto_20211125_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='description',
            field=models.CharField(default='Empty', max_length=120),
        ),
    ]
