# Generated by Django 3.2.8 on 2021-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_auto_20211126_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='clustermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='cluster_name',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clustermodel',
            name='description',
            field=models.CharField(default='Empty', max_length=600),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='body',
            field=models.CharField(default='Empty', max_length=2000),
        ),
    ]
