# Generated by Django 3.2.8 on 2021-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_notemodel_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='body',
            field=models.CharField(default='Empty', max_length=15000),
        ),
    ]
