# Generated by Django 3.2.8 on 2021-12-13 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cluster', '0006_alter_notemodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='is_verified_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clustermodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClusterModel_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
