# Generated by Django 3.2.8 on 2021-12-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_auto_20211213_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='cover',
            field=models.ImageField(default='exes', upload_to='note_cover'),
            preserve_default=False,
        ),
    ]
