# Generated by Django 3.2.8 on 2022-03-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0009_auto_20211218_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NoteStatsModel_NoteModel', to='cluster.notemodel')),
            ],
        ),
    ]
