# Generated by Django 3.2.8 on 2022-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_notestatsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustermodel',
            name='description',
            field=models.TextField(default='Empty', max_length=600),
        ),
    ]
