# Generated by Django 3.2.15 on 2022-10-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_alter_clustermodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClusterGallery_ClusterModel', to='cluster.clustermodel')),
            ],
        ),
    ]
