# Generated by Django 3.2.18 on 2023-03-15 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cluster', '0015_auto_20230228_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermodel',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
