# Generated by Django 3.2.18 on 2023-03-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0016_clustermodel_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteStatsViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NoteStatsModel_NoteModel', to='cluster.notemodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='notestatsmodel',
            name='note',
        ),
        migrations.DeleteModel(
            name='ClusterGallery',
        ),
        migrations.DeleteModel(
            name='NoteStatsModel',
        ),
    ]
