# Generated by Django 3.2.20 on 2023-11-17 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cluster', '0017_auto_20230322_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliffNoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(default='Empty', max_length=500)),
                ('pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CliffNoteModel_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
