# Generated by Django 3.2.20 on 2023-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0018_cliffnotemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliffnotemodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
