# Generated by Django 3.2.23 on 2024-01-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0019_cliffnotemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
