# Generated by Django 3.2.23 on 2024-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0020_notemodel_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='body',
            field=models.TextField(default='Empty', max_length=1000000),
        ),
    ]
