name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: cp template.env .env

      - name: Build and start Docker containers
        run: docker-compose -f docker-compose.yml up -d --build 

      - name: Wait for Django to start
        run: |
          timeout=120  # Increase the timeout to 2 minutes
          start_time=$(date +%s)
          while true; do
            echo "Checking if Django is ready..."
            http_status_code=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8000)
            echo "HTTP Status Code: $http_status_code"
            if [[ "$http_status_code" == "200" ]]; then
              echo "Django is ready!"
              break
            else
              echo "Django did not return HTTP status code 200. Retrying..."
            fi

            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))

            if [[ $elapsed_time -ge $timeout ]]; then
              echo "Timeout reached. Django did not start within $timeout seconds. Last HTTP Status Code: $http_status_code"
              exit 1
            fi

            sleep 5
          done

      - name: Run Django tests
        run: docker exec k9archiver_django python manage.py test

      - name: Stop and remove Docker containers
        run: docker-compose down
